name: Maestro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Baixa e instala o Maestro CLI diretamente
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo 'export PATH="$HOME/.maestro/bin:$PATH"' >> $GITHUB_ENV

      # Passo 3: Configura a API Key do Maestro
      - name: Set Maestro API Key
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: echo "MAESTRO_API_KEY=$MAESTRO_API_KEY" >> $GITHUB_ENV

      # Passo 4: Login no Maestro Cloud (com o PATH atualizado)
      - name: Login to Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: |
          source $GITHUB_ENV
          maestro cloud login $MAESTRO_API_KEY

      # Passo 5: Executa os testes no Maestro Cloud
      - name: Run Tests on Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: |
          source $GITHUB_ENV
          maestro cloud <appBinary> <flowFile>
