name: iOS CI Test with Maestro

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Unzip Wikipedia.app
        run: |
          unzip -o -q samples/wikipedia.zip -d samples

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14"
          sleep 30

      - name: Run Maestro Tests
        env:
          MAESTRO_CLI_NO_ANALYTICS: "true"
        run: |
          maestro test --format=JUNIT --output=maestro-test-report.xml samples/ios-advanced-flow.yaml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: maestro-test-report
          path: maestro-test-report.xml
