name: iOS CI Test with Maestro

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Unzip Wikipedia.app
        run: |
          unzip -o -q samples/wikipedia.zip -d samples

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "export PATH=\"$PATH:$HOME/.maestro/bin\"" >> $HOME/.bash_profile
          source $HOME/.bash_profile
          maestro --version # Verificar se o Maestro foi instalado corretamente

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14"
          sleep 30

      - name: Run Maestro Tests
        env:
          MAESTRO_CLI_NO_ANALYTICS: "true"
        run: |
          source $HOME/.bash_profile
          maestro test --format=JUNIT --output=maestro-test-report.xml samples/ios-advanced-flow.yaml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: maestro-test-report
          path: maestro-test-report.xml
