name: Maestro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: List required files
        run: |
          echo "Listing files in the samples directory:"
          ls -R samples

      # REMOVA OU COMENTE O LOGIN NO MAESTRO CLOUD SE NÃO FOR NECESSÁRIO
      # - name: Login to Maestro Cloud
      #   env:
      #     MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
      #   run: maestro cloud login $MAESTRO_API_KEY

      - name: Run Tests Locally on GitHub Runner
        run: |
          maestro test "samples/Wikipedia.app" "samples/ios-advanced-flow.yaml" \
          --subflow "samples/subflows/launch-clearstate-ios.yaml" \
          --script "samples/scripts/getSearchQuery.js"
