name: Maestro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Baixa e instala o Maestro CLI diretamente em uma pasta conhecida
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH  # Adiciona ao PATH diretamente

      # Passo 3: Login no Maestro Cloud usando a API Key
      - name: Login to Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: maestro cloud login $MAESTRO_API_KEY

      # Passo 4: Executa os testes no Maestro Cloud com o caminho correto dos arquivos
      - name: Run Tests on Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: maestro cloud "samples/sample.zip" "samples/ios-flow.yaml"
