name: Maestro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: List required files
        run: |
          echo "Listing files in the samples directory:"
          ls -R samples

      - name: Unzip Wikipedia.app
        run: |
          unzip samples/wikipedia.zip -d samples
          echo "Listing files in Wikipedia.app directory after unzip:"
          ls -R samples/Wikipedia.app

      - name: Run Tests Locally on GitHub Runner
        env:
          MAESTRO_CLI_NO_ANALYTICS: 1  # Para desativar analytics no CI
        run: |
          maestro test samples/ios-advanced-flow.yaml
