name: Maestro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Instala o Maestro CLI
      - name: Install Maestro CLI
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      # Passo 3: Verifica se os arquivos necessários estão no lugar
      - name: List required files
        run: |
          echo "Listing files in the samples directory:"
          ls -R samples   # Mostra a estrutura completa dentro de samples para garantir que os caminhos estão corretos

      # Passo 4: Login no Maestro Cloud usando a API Key
      - name: Login to Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: maestro cloud login $MAESTRO_API_KEY

      # Passo 5: Executa o teste principal, que depende dos subfluxos e do script
      - name: Run Tests on Maestro Cloud
        env:
          MAESTRO_API_KEY: ${{ secrets.MAESTRO_API_KEY }}
        run: |
          # Comando para rodar o teste principal com os caminhos corretos
          maestro cloud "samples/Wikipedia.app" "samples/ios-advanced-flow.yaml" \
          --subflow "samples/subflows/launch-clearstate-ios.yaml" \
          --script "samples/scripts/getSearchQuery.js"
